# Generated by Django 2.0.4 on 2018-11-30 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('author', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=50)),
                ('img', models.TextField()),
                ('_from', models.CharField(max_length=50)),
                ('digest', models.CharField(max_length=500)),
                ('content', models.TextField()),
                ('show', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Article_category1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('level', models.IntegerField(default=1)),
                ('father', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.Article_category1')),
            ],
        ),
        migrations.AddField(
            model_name='article1',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.Article_category1'),
        ),
    ]
