# Generated by Django 2.0.4 on 2018-11-30 01:14

import app1.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article1',
            name='category',
            field=models.ForeignKey(null=True, on_delete=models.SET(app1.models.get_sentinel_category), to='app1.Article_category1'),
        ),
    ]
