# Generated by Django 2.0.4 on 2018-11-30 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20181130_0114'),
    ]

    operations = [
        migrations.AddField(
            model_name='article1',
            name='order',
            field=models.IntegerField(null=True),
        ),
    ]
