# Generated by Django 2.0.4 on 2018-11-30 20:28

import app1.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20181130_0330'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=50)),
                ('img', models.TextField()),
                ('digest', models.CharField(max_length=500)),
                ('content', models.TextField()),
                ('price', models.CharField(max_length=100)),
                ('origin_price', models.CharField(max_length=100)),
                ('show', models.IntegerField(default=1)),
                ('order', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product_categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('level', models.IntegerField(default=1)),
                ('father', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.Product_categories')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=models.SET(app1.models.get_sentinel_product_category), to='app1.Product_categories'),
        ),
    ]
