# Generated by Django 2.0.4 on 2018-12-03 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImgName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_name', models.CharField(max_length=100)),
                ('img_name_with_suffix', models.CharField(max_length=100)),
            ],
        ),
    ]
