# Generated by Django 2.0.4 on 2018-12-03 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_clientforms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientforms',
            name='have_pic',
        ),
        migrations.RemoveField(
            model_name='clientforms',
            name='pics_names',
        ),
    ]
