# Generated by Django 2.0.4 on 2018-12-03 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_auto_20181203_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientforms',
            name='openid',
            field=models.CharField(default='测试', max_length=100),
        ),
    ]
