# Generated by Django 2.0.4 on 2018-12-03 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_clientforms_openid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trade',
            old_name='status',
            new_name='money_status',
        ),
    ]
