# Generated by Django 2.0.4 on 2018-12-03 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_auto_20181203_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='trade_status',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
