# Generated by Django 2.0.4 on 2018-12-03 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_trade_trade_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telephone',
            field=models.CharField(default='', max_length=50),
        ),
    ]
