# Generated by Django 2.0.4 on 2018-12-05 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_trade_notify_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='oid',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
