# Generated by Django 2.0.4 on 2018-12-06 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_trade_pay_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiveEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
            ],
        ),
    ]
