# Generated by Django 2.0.4 on 2018-12-09 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0018_receiveemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientforms',
            name='time',
            field=models.DateTimeField(null=True),
        ),
    ]
